version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app:delegated

  mongo:
    image: mongo
    ports:
      - "27017:27017"
